services:
  cryostat:
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      QUARKUS_LANGCHAIN4J_OLLAMA_BASE_URL: http://ollama:11434
      QUARKUS_LANGCHAIN4J_OLLAMA_LOG_REQUESTS: "true"
      QUARKUS_LANGCHAIN4J_OLLAMA_LOG_RESPONSES: "true"
  ollama:
    deploy:
      resources:
        limits:
          cpus: "6"
          memory: 24GiB
    init: true
    image: ${CRYOSTAT_OLLAMA_IMAGE:-ollama/ollama:latest}
    hostname: ollama
    restart: always
    expose:
      - "11434"
    environment:
      OLLAMA_HOST: 0.0.0.0
      OLLAMA_NUM_THREADS: "6"
      OLLAMA_KEEP_ALIVE: "-1"
    volumes:
      - ollama:/root/.ollama
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/11434' || exit 1
      interval: 10s
      retries: 3
      start_period: 10s
      timeout: 10s

volumes:
  ollama:
    external: true
