services:
  cryostat:
    environment:
      - QUARKUS_LANGCHAIN4J_OLLAMA_BASE_URL=http://ollama:11434
      - QUARKUS_LANGCHAIN4J_OLLAMA_CHAT_MODEL_MODEL_ID=${CRYOSTAT_OLLAMA_MODEL:-granite4:micro}
      - QUARKUS_LANGCHAIN4J_OLLAMA_LOG_REQUESTS=true
      - QUARKUS_LANGCHAIN4J_OLLAMA_LOG_RESPONSES=true
  ollama:
    init: true
    image: ${CRYOSTAT_OLLAMA_IMAGE:-ollama/ollama:latest}
    hostname: ollama
    restart: always
    expose:
      - "11434"
    volumes:
      - ollama:/root/.ollama

volumes:
  ollama:
    external: true
